Sms templates
inensus/MPManager pull request #165
Opened 2021-03-08 15:47 UTC by 93Kamuran

SMS settings page created.
The infrastructure of parsing parametric SMS sentences is created.

2021-03-12 22:31 UTC, alchalade requested changes

2021-03-12 22:31 UTC, alchalade commented on Website/htdocs/mpmanager/app/Sms/Senders/SmsSender.php
> +        $this->validateReferences();
Suggestion: move that logic to sendSms .

2021-03-12 22:31 UTC, alchalade commented on Website/htdocs/mpmanager/app/Sms/Senders/SmsSender.php
> +    private function validateReferences()
you could use it to call the preparation methods if the key is in the references array

2021-03-12 22:31 UTC, alchalade commented on Website/htdocs/mpmanager/app/Sms/Senders/SmsSender.php
> +    public function prepareHeader()
That part will break if the given reference is not stored in the database, error handling missing.

2021-03-14 09:45 UTC, 93Kamuran commented on Website/htdocs/mpmanager/app/Sms/Senders/SmsSender.php
> +                Log::debug('Send sms rejected, some of sms bodies are null', ['Sms Bodies' => $nullSmsBodies]);
Critical Log applied.

2021-03-14 09:47 UTC, 93Kamuran commented on Website/htdocs/mpmanager/app/Http/Controllers/TransactionController.php
> -
I don't understand that.

2021-03-14 10:08 UTC, 93Kamuran commented on Website/htdocs/mpmanager/app/Http/Controllers/SmsController.php
>          $this->meterParameter = $meterParameter;
Please check it again, I don't understand.

2021-04-07 07:44 UTC, merged